// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetAlertsData, GetAlertsErrors, GetAlertsResponses, GetHostsData, GetHostsErrors, GetHostsResponses, GetOverviewData, GetOverviewErrors, GetOverviewResponses, GetPagesData, GetPagesErrors, GetPagesResponses, GetReferrersData, GetReferrersErrors, GetReferrersResponses, GetReportsData, GetReportsErrors, GetReportsResponses, GetSettingsData, GetSettingsErrors, GetSettingsResponses, GetSubscribersData, GetSubscribersErrors, GetSubscribersResponses, GetSubscriptionData, GetSubscriptionErrors, GetSubscriptionResponses, PostRecomputeData, PostRecomputeErrors, PostRecomputeResponses, PutSubscriptionData, PutSubscriptionErrors, PutSubscriptionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getAlerts = <ThrowOnError extends boolean = false>(options?: Options<GetAlertsData, ThrowOnError>): RequestResult<GetAlertsResponses, GetAlertsErrors, ThrowOnError> => (options?.client ?? client).get<GetAlertsResponses, GetAlertsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/errordashboard/api/v1/alerts',
    ...options
});

export const getHosts = <ThrowOnError extends boolean = false>(options?: Options<GetHostsData, ThrowOnError>): RequestResult<GetHostsResponses, GetHostsErrors, ThrowOnError> => (options?.client ?? client).get<GetHostsResponses, GetHostsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/errordashboard/api/v1/hosts',
    ...options
});

export const getOverview = <ThrowOnError extends boolean = false>(options?: Options<GetOverviewData, ThrowOnError>): RequestResult<GetOverviewResponses, GetOverviewErrors, ThrowOnError> => (options?.client ?? client).get<GetOverviewResponses, GetOverviewErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/errordashboard/api/v1/overview',
    ...options
});

export const getPages = <ThrowOnError extends boolean = false>(options?: Options<GetPagesData, ThrowOnError>): RequestResult<GetPagesResponses, GetPagesErrors, ThrowOnError> => (options?.client ?? client).get<GetPagesResponses, GetPagesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/errordashboard/api/v1/pages',
    ...options
});

export const postRecompute = <ThrowOnError extends boolean = false>(options?: Options<PostRecomputeData, ThrowOnError>): RequestResult<PostRecomputeResponses, PostRecomputeErrors, ThrowOnError> => (options?.client ?? client).post<PostRecomputeResponses, PostRecomputeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/errordashboard/api/v1/recompute',
    ...options
});

export const getReferrers = <ThrowOnError extends boolean = false>(options?: Options<GetReferrersData, ThrowOnError>): RequestResult<GetReferrersResponses, GetReferrersErrors, ThrowOnError> => (options?.client ?? client).get<GetReferrersResponses, GetReferrersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/errordashboard/api/v1/referrers',
    ...options
});

export const getReports = <ThrowOnError extends boolean = false>(options?: Options<GetReportsData, ThrowOnError>): RequestResult<GetReportsResponses, GetReportsErrors, ThrowOnError> => (options?.client ?? client).get<GetReportsResponses, GetReportsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/errordashboard/api/v1/reports',
    ...options
});

export const getSettings = <ThrowOnError extends boolean = false>(options?: Options<GetSettingsData, ThrowOnError>): RequestResult<GetSettingsResponses, GetSettingsErrors, ThrowOnError> => (options?.client ?? client).get<GetSettingsResponses, GetSettingsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/errordashboard/api/v1/settings',
    ...options
});

export const getSubscribers = <ThrowOnError extends boolean = false>(options?: Options<GetSubscribersData, ThrowOnError>): RequestResult<GetSubscribersResponses, GetSubscribersErrors, ThrowOnError> => (options?.client ?? client).get<GetSubscribersResponses, GetSubscribersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/errordashboard/api/v1/subscribers',
    ...options
});

export const getSubscription = <ThrowOnError extends boolean = false>(options?: Options<GetSubscriptionData, ThrowOnError>): RequestResult<GetSubscriptionResponses, GetSubscriptionErrors, ThrowOnError> => (options?.client ?? client).get<GetSubscriptionResponses, GetSubscriptionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/errordashboard/api/v1/subscription',
    ...options
});

export const putSubscription = <ThrowOnError extends boolean = false>(options?: Options<PutSubscriptionData, ThrowOnError>): RequestResult<PutSubscriptionResponses, PutSubscriptionErrors, ThrowOnError> => (options?.client ?? client).put<PutSubscriptionResponses, PutSubscriptionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/errordashboard/api/v1/subscription',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});
