// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44366/' | (string & {});
};

export type AlertResponseModel = {
    id: number;
    raisedUtc: string;
    windowStartUtc: string;
    host: string;
    observed: number;
    median: number;
    score: number;
    recipientCount: number;
    topPaths: Array<string>;
};

export type AnomalyExplanation = 'InsufficientHistory' | 'BelowFloor' | 'BelowRatio' | 'WithinSpread' | 'Anomalous';

export type AnomalyStateResponseModel = {
    isAnomalous: boolean;
    observed: number;
    median: number;
    scale: number;
    score: number;
    baselineDays: number;
    explanation: AnomalyExplanation;
    explanationArgs: Array<number>;
};

export type DailyPointResponseModel = {
    date: string;
    count: number;
    weightedCount: number;
    estimatedRequests: number;
};

export type ErrorTypeCountResponseModel = {
    type: string;
    count: number;
};

export type OffendingPageResponseModel = {
    host: string;
    path: string;
    type: string;
    statusCode?: null | number;
    count: number;
    firstSeenUtc: string;
    lastSeenUtc: string;
    documentKey?: null | string;
    isUnpublished: boolean;
    hasReferrers: boolean;
};

export type OverviewResponseModel = {
    series: Array<DailyPointResponseModel>;
    byType: Array<ErrorTypeCountResponseModel>;
    byStatus: Array<StatusCountResponseModel>;
    observedLast24Hours: number;
    anomaly?: null | AnomalyStateResponseModel;
    pendingRawReports: number;
    lastAggregatedUtc?: null | string;
    hosts: Array<string>;
};

export type PagedAlertResponseModel = {
    total: number;
    items: Array<AlertResponseModel>;
};

export type PagedOffendingPageResponseModel = {
    total: number;
    items: Array<OffendingPageResponseModel>;
};

export type PagedRawReportResponseModel = {
    total: number;
    items: Array<RawReportResponseModel>;
};

export type PageSortField = 'Count' | 'LastSeen' | 'Path';

export type RawReportResponseModel = {
    id: number;
    receivedUtc: string;
    occurredUtc: string;
    url: string;
    type: string;
    phase: string;
    statusCode?: null | number;
    method?: null | string;
    protocol?: null | string;
    serverIp?: null | string;
    referrer?: null | string;
    elapsedTimeMs?: null | number;
};

export type RecomputeResponseModel = {
    rowsAggregated: number;
    rowsPruned: number;
    alertRaised: boolean;
};

export type ReferrerResponseModel = {
    referrer?: null | string;
    count: number;
    lastSeenUtc: string;
};

export type ReferrersResponseModel = {
    items: Array<ReferrerResponseModel>;
    availableDays: number;
};

export type SettingsResponseModel = {
    enabled: boolean;
    reportPath: string;
    successFraction: number;
    failureFraction: number;
    rawRetentionDays: number;
    rateLimitPerMinute: number;
    acceptedHosts: Array<string>;
    alertsEnabled: boolean;
    baselineDays: number;
    minBaselineDays: number;
    scoreThreshold: number;
    minObserved: number;
    minRatio: number;
    cooldownHours: number;
    canSendEmail: boolean;
};

export type SortDirection = 'Ascending' | 'Descending';

export type StatusCountResponseModel = {
    statusCode: number;
    count: number;
};

export type SubscriberResponseModel = {
    userKey: string;
    name: string;
    email: string;
    language?: null | string;
    lastNotifiedUtc?: null | string;
};

export type SubscriptionResponseModel = {
    enabled: boolean;
    canReceiveEmail: boolean;
    lastNotifiedUtc?: null | string;
};

export type UpdateSubscriptionRequestModel = {
    enabled: boolean;
};

export type GetAlertsData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/errordashboard/api/v1/alerts';
};

export type GetAlertsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAlertsResponses = {
    /**
     * OK
     */
    200: PagedAlertResponseModel;
};

export type GetAlertsResponse = GetAlertsResponses[keyof GetAlertsResponses];

export type GetHostsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/errordashboard/api/v1/hosts';
};

export type GetHostsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetHostsResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetHostsResponse = GetHostsResponses[keyof GetHostsResponses];

export type GetOverviewData = {
    body?: never;
    path?: never;
    query?: {
        days?: number;
        host?: string;
    };
    url: '/umbraco/errordashboard/api/v1/overview';
};

export type GetOverviewErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetOverviewResponses = {
    /**
     * OK
     */
    200: OverviewResponseModel;
};

export type GetOverviewResponse = GetOverviewResponses[keyof GetOverviewResponses];

export type GetPagesData = {
    body?: never;
    path?: never;
    query?: {
        days?: number;
        host?: string;
        type?: string;
        statusCode?: number;
        skip?: number;
        take?: number;
        orderBy?: PageSortField;
        direction?: SortDirection;
    };
    url: '/umbraco/errordashboard/api/v1/pages';
};

export type GetPagesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetPagesResponses = {
    /**
     * OK
     */
    200: PagedOffendingPageResponseModel;
};

export type GetPagesResponse = GetPagesResponses[keyof GetPagesResponses];

export type PostRecomputeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/errordashboard/api/v1/recompute';
};

export type PostRecomputeErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type PostRecomputeResponses = {
    /**
     * OK
     */
    200: RecomputeResponseModel;
};

export type PostRecomputeResponse = PostRecomputeResponses[keyof PostRecomputeResponses];

export type GetReferrersData = {
    body?: never;
    path?: never;
    query?: {
        host?: string;
        path?: string;
        days?: number;
        take?: number;
    };
    url: '/umbraco/errordashboard/api/v1/referrers';
};

export type GetReferrersErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetReferrersResponses = {
    /**
     * OK
     */
    200: ReferrersResponseModel;
};

export type GetReferrersResponse = GetReferrersResponses[keyof GetReferrersResponses];

export type GetReportsData = {
    body?: never;
    path?: never;
    query?: {
        host?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/errordashboard/api/v1/reports';
};

export type GetReportsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetReportsResponses = {
    /**
     * OK
     */
    200: PagedRawReportResponseModel;
};

export type GetReportsResponse = GetReportsResponses[keyof GetReportsResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/errordashboard/api/v1/settings';
};

export type GetSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: SettingsResponseModel;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type GetSubscribersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/errordashboard/api/v1/subscribers';
};

export type GetSubscribersErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetSubscribersResponses = {
    /**
     * OK
     */
    200: Array<SubscriberResponseModel>;
};

export type GetSubscribersResponse = GetSubscribersResponses[keyof GetSubscribersResponses];

export type GetSubscriptionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/errordashboard/api/v1/subscription';
};

export type GetSubscriptionErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSubscriptionResponses = {
    /**
     * OK
     */
    200: SubscriptionResponseModel;
};

export type GetSubscriptionResponse = GetSubscriptionResponses[keyof GetSubscriptionResponses];

export type PutSubscriptionData = {
    body: UpdateSubscriptionRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/errordashboard/api/v1/subscription';
};

export type PutSubscriptionErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PutSubscriptionResponses = {
    /**
     * OK
     */
    200: SubscriptionResponseModel;
};

export type PutSubscriptionResponse = PutSubscriptionResponses[keyof PutSubscriptionResponses];
